<?php

/**
 * Dynamic service detail pages keyed by URL slug.
 * Route: /services/{slug}  →  services.show
 */
return [

    'ship-spares-logistics' => [
        'title' => 'Ship Spares Logistics',
        'category' => 'marine_logistics',
        'category_title' => 'Marine Logistics',
        'meta_title' => 'Ship Spares Logistics | Door-to-Deck | MarineCaddie',
        'meta_description' => '24/7 ship spare logistics from supplier to vessel—documentation, customs, carriers, and last-mile onboard delivery at global ports.',
        'meta_keywords' => 'ship spares logistics, door to deck, maritime spare parts, vessel spare delivery, MarineCaddie',
        'excerpt' => 'Time-critical spare parts moved from supplier to deck with full documentation and port-aware last-mile delivery.',
        'intro' => 'When a vessel cannot wait, spare parts logistics becomes the critical path. MarineCaddie coordinates pickup, packing, export/import paperwork, carrier selection, customs, and onboard handover so your fleet stays moving.',
        'hero_image' => 'assets/img/services/service-05.jpg',
        'gallery' => [
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-03.jpg',
        ],
        'highlights' => [
            'Door-to-deck coverage with proof of delivery',
            'Supplier pickup and export packing for maritime urgency',
            'Customs and TP/trans-shipment aligned to vessel ETA',
            'Air, ocean, road, and hand-carry options as needed',
            '24/7 coordination for breakdown and AOG-style demand',
            'Single point of contact from enquiry to onboard receipt',
        ],
        'process' => [
            ['title' => 'Brief & confirm', 'text' => 'Part details, vessel, port, and required delivery window.'],
            ['title' => 'Move & clear', 'text' => 'Carrier booking, documentation, and customs clearances.'],
            ['title' => 'Last mile', 'text' => 'Port coordination and onboard delivery with handover notes.'],
            ['title' => 'Close out', 'text' => 'POD, invoices, and status updates for your operations team.'],
        ],
        'faqs' => [
            ['q' => 'Do you handle AOG / breakdown spares?', 'a' => 'Yes. We prioritise time-critical ship spares with express air, courier, or hand-carry options when the schedule demands it.'],
            ['q' => 'Which regions do you cover?', 'a' => 'We support global port calls with presence and partners across Dubai, India, Asia, Europe, Africa, and the USA.'],
            ['q' => 'Can you manage customs as part of the move?', 'a' => 'Customs clearance and TP/trans-shipment can be bundled so spare parts reach the vessel without handoff gaps.'],
        ],
        'related' => ['onboard-delivery', 'vessel-husbandry', 'air-freight', 'import-clearance'],
    ],

    'onboard-delivery' => [
        'title' => 'Onboard Delivery',
        'category' => 'marine_logistics',
        'category_title' => 'Marine Logistics',
        'meta_title' => 'Onboard Delivery to Vessel | MarineCaddie Shipping',
        'meta_description' => 'Last-mile onboard delivery of ship spares and supplies—launch, berth, or terminal handover coordinated to your vessel schedule.',
        'meta_keywords' => 'onboard delivery, ship delivery, vessel last mile, launch delivery, MarineCaddie',
        'excerpt' => 'Precise last-mile handover to the vessel—timed to berth, anchorage, or terminal windows.',
        'intro' => 'Getting cargo to the port is only half the job. Our onboard delivery teams align with ship agents, launch services, and terminal rules so consignments reach the Master or chief engineer as planned.',
        'hero_image' => 'assets/img/services/service-01.jpg',
        'gallery' => [
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-01.jpg',
        ],
        'highlights' => [
            'Berth, anchorage, and terminal-aware handovers',
            'Coordination with agents and launch boat operators',
            'Secure packing and labelling for deck receipt',
            'Photo and signature proof of delivery',
            'Integration with ship spares and husbandry jobs',
            'After-hours and weekend vessel call support',
        ],
        'process' => [
            ['title' => 'Port readiness', 'text' => 'Confirm berth/anchorage, agent contacts, and access rules.'],
            ['title' => 'Staging', 'text' => 'Stage cargo near the terminal or launch point.'],
            ['title' => 'Handover', 'text' => 'Deliver onboard with documented receipt.'],
            ['title' => 'Report', 'text' => 'Share POD and exceptions with your desk immediately.'],
        ],
        'faqs' => [
            ['q' => 'Can you deliver at anchorage?', 'a' => 'Where local regulations and launch availability allow, we arrange anchorage delivery via approved launch services.'],
            ['q' => 'What if the vessel ETA shifts?', 'a' => 'We re-sequence staging and delivery windows with the agent so handover stays aligned to the new call time.'],
            ['q' => 'Is onboard delivery available with spare logistics?', 'a' => 'Yes—door-to-deck packages routinely include our last-mile onboard step.'],
        ],
        'related' => ['ship-spares-logistics', 'port-coordination', 'vessel-husbandry'],
    ],

    'ship-agency-support' => [
        'title' => 'Ship Agency Support',
        'category' => 'marine_logistics',
        'category_title' => 'Marine Logistics',
        'meta_title' => 'Ship Agency Support | Port Call Coordination | MarineCaddie',
        'meta_description' => 'Practical ship agency support for port calls—coordination, documentation liaison, and operations cover that keeps vessel turns efficient.',
        'meta_keywords' => 'ship agency support, port agency, vessel agency, marine agency, MarineCaddie',
        'excerpt' => 'Agency-backed port call support so arrivals, clearances, and husbandry tasks stay aligned.',
        'intro' => 'MarineCaddie provides ship agency support that connects logistics and vessel operations—helping principals, owners, and managers navigate documentation, authorities, and on-the-ground counterparts during the call.',
        'hero_image' => 'assets/img/services/service-03.jpg',
        'gallery' => [
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-02.jpg',
        ],
        'highlights' => [
            'Pre-arrival planning and stakeholder coordination',
            'Liaison with terminals, authorities, and suppliers',
            'Husbandry and logistics requests under one desk',
            'Clear status reporting for owners and charterers',
            'Support across key Indian Ocean and Asian ports',
            'Aligned with crew, spare, and customs workflows',
        ],
        'process' => [
            ['title' => 'Nomination', 'text' => 'Receive vessel particulars, ETA, and scope of agency support.'],
            ['title' => 'Pre-arrival', 'text' => 'Align services, documentation, and berth/terminal expectations.'],
            ['title' => 'During call', 'text' => 'Coordinate attending parties and resolve operational snags.'],
            ['title' => 'Departure', 'text' => 'Close paperwork and share a concise call summary.'],
        ],
        'faqs' => [
            ['q' => 'Is this a full port agency appointment?', 'a' => 'We provide agency-style operational support and can work alongside appointed agents or act as your coordinating partner depending on the port and nomination.'],
            ['q' => 'Can husbandry be included?', 'a' => 'Yes. Vessel husbandry, crew logistics, and spare deliveries are frequently combined with agency support.'],
            ['q' => 'How do you report status?', 'a' => 'You receive timely updates by email/phone—pre-arrival, alongside, and post-departure as agreed.'],
        ],
        'related' => ['vessel-husbandry', 'port-coordination', 'crew-logistics'],
    ],

    'vessel-husbandry' => [
        'title' => 'Vessel Husbandry',
        'category' => 'marine_logistics',
        'category_title' => 'Marine Logistics',
        'meta_title' => 'Vessel Husbandry & Port Support | MarineCaddie',
        'meta_description' => 'Vessel husbandry and port support across India, Sri Lanka, Indonesia & Singapore—crew, supplies, medical, and operational assistance.',
        'meta_keywords' => 'vessel husbandry, port husbandry, port support, ship husbandry, MarineCaddie',
        'excerpt' => 'Hands-on husbandry so every port call stays efficient—from crew change to dry-dock assist.',
        'intro' => 'Our husbandry desk focuses on practical vessel needs during the call: crew movements, stores, medical, cash-to-master coordination, and local logistics—backed by regional coverage in India, Sri Lanka, Indonesia, and Singapore.',
        'hero_image' => 'assets/img/services/service-06.jpg',
        'gallery' => [
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-02.jpg',
        ],
        'highlights' => [
            'Port agency-aligned husbandry execution',
            'Crew change, immigration, and visa assistance',
            'Stores, chandling, and fresh water coordination',
            'Medical assistance and cash-to-master support',
            'Launch boats and bunkering coordination',
            'Coverage across India, Sri Lanka, Indonesia & Singapore',
        ],
        'process' => [
            ['title' => 'Scope', 'text' => 'Confirm husbandry checklist and call timings.'],
            ['title' => 'Arrange', 'text' => 'Book vendors, transport, and authority appointments.'],
            ['title' => 'Attend', 'text' => 'Execute alongside with live updates to your desk.'],
            ['title' => 'Reconcile', 'text' => 'Share costs, receipts, and completion notes.'],
        ],
        'faqs' => [
            ['q' => 'Which ports do you support for husbandry?', 'a' => 'Primary husbandry coverage is India, Sri Lanka, Indonesia, and Singapore, with partner support on additional routes.'],
            ['q' => 'Can you combine husbandry with spare delivery?', 'a' => 'Yes—spares logistics and onboard delivery are frequently scheduled into the same call window.'],
            ['q' => 'Do you assist dry dock calls?', 'a' => 'We support dry-dock related husbandry and logistics coordination where nominated.'],
        ],
        'related' => ['crew-logistics', 'ship-agency-support', 'port-coordination', 'onboard-delivery'],
    ],

    'crew-logistics' => [
        'title' => 'Crew Logistics',
        'category' => 'marine_logistics',
        'category_title' => 'Marine Logistics',
        'meta_title' => 'Crew Logistics & Crew Change | MarineCaddie',
        'meta_description' => 'Crew logistics for sign-on/sign-off—transport, immigration liaison, hotels, and timed vessel embarkation coordinated with your port call.',
        'meta_keywords' => 'crew logistics, crew change, seafarer logistics, sign on sign off, MarineCaddie',
        'excerpt' => 'Smooth crew movements—airport to vessel and vessel to hotel—timed to immigration and sailing schedules.',
        'intro' => 'Crew changes fail when timing slips. We coordinate flights, land transport, hotel, immigration paperwork liaison, and embarkation so seafarers join or leave the vessel without delaying the call.',
        'hero_image' => 'assets/img/services/service-02.jpg',
        'gallery' => [
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-03.jpg',
        ],
        'highlights' => [
            'Sign-on / sign-off planning around ETA/ETD',
            'Airport meets, hotels, and secure transfers',
            'Immigration and visa assistance liaison',
            'PPE and document bag handling when required',
            'Medical referrals coordinated with husbandry',
            'Single reporting line for owners and managers',
        ],
        'process' => [
            ['title' => 'Manifest', 'text' => 'Collect crew list, flights, and visa status.'],
            ['title' => 'Sequence', 'text' => 'Build transfer times against immigration hours.'],
            ['title' => 'Move', 'text' => 'Execute meets, hotels, and vessel embarkation.'],
            ['title' => 'Confirm', 'text' => 'Close with boarding confirmation and cost notes.'],
        ],
        'faqs' => [
            ['q' => 'Do you book hotels and taxis?', 'a' => 'Yes. Landside logistics—hotels, transfers, and airport handling—are part of our crew logistics package.'],
            ['q' => 'Can you help with visa issues?', 'a' => 'We liaise on visa and immigration requirements; approvals remain subject to local authority rules.'],
            ['q' => 'Is night embarkation possible?', 'a' => 'Where the terminal/agent and authorities allow, we schedule off-hour movements.'],
        ],
        'related' => ['vessel-husbandry', 'port-coordination', 'ship-agency-support'],
    ],

    'port-coordination' => [
        'title' => 'Port Coordination',
        'category' => 'marine_logistics',
        'category_title' => 'Marine Logistics',
        'meta_title' => 'Port Coordination Services | MarineCaddie',
        'meta_description' => 'Port coordination that syncs terminals, agents, transporters, and suppliers so vessel calls and cargo movements stay on schedule.',
        'meta_keywords' => 'port coordination, port operations, terminal coordination, vessel call planning, MarineCaddie',
        'excerpt' => 'One coordination layer across terminals, transporters, and vessel stakeholders.',
        'intro' => 'Complex calls involve many parties. MarineCaddie acts as the coordination hub—keeping cargo, crew, husbandry, and documentation stakeholders working from the same timeline.',
        'hero_image' => 'assets/img/services/service-04.jpg',
        'gallery' => [
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-03.jpg',
        ],
        'highlights' => [
            'Shared timeline for ETA, berth, and cargo cut-offs',
            'Terminal and transporter liaison',
            'Exception handling when windows slip',
            'Combined views of spare, crew, and customs tasks',
            'Clear escalation path to our ops desk',
            'Post-call summary for continuous improvement',
        ],
        'process' => [
            ['title' => 'Map parties', 'text' => 'Identify every stakeholder and decision owner.'],
            ['title' => 'Build plan', 'text' => 'Publish a call plan with critical timestamps.'],
            ['title' => 'Run desk', 'text' => 'Monitor execution and unblock issues live.'],
            ['title' => 'Debrief', 'text' => 'Capture learnings and close the file cleanly.'],
        ],
        'faqs' => [
            ['q' => 'Is port coordination only for large projects?', 'a' => 'No. Even single spare deliveries benefit from coordinated cut-offs and agent alignment.'],
            ['q' => 'Can you coordinate multimodal legs into the port?', 'a' => 'Yes—air, ocean, and road segments can be sequenced into the same call plan.'],
            ['q' => 'How do we start?', 'a' => 'Share vessel schedule and required services; we return a coordination plan within your timeline.'],
        ],
        'related' => ['ship-agency-support', 'onboard-delivery', 'multimodal-transport'],
    ],

    'air-freight' => [
        'title' => 'Air Freight',
        'category' => 'freight_forwarding',
        'category_title' => 'Freight Forwarding',
        'meta_title' => 'Air Freight for Maritime Cargo | MarineCaddie',
        'meta_description' => 'Time-critical air freight for maritime cargo—airport-to-port lanes, express options, and documentation built for vessel urgency.',
        'meta_keywords' => 'air freight, maritime air cargo, express air freight, ship spare air freight, MarineCaddie',
        'excerpt' => 'Fast air lanes for urgent maritime cargo when schedules cannot slip.',
        'intro' => 'Air freight is often the difference between sailing on time and costly delays. We design airport-to-port moves with maritime paperwork, temperature or handling notes when needed, and clear milestones to your vessel ETA.',
        'hero_image' => 'assets/img/services/service-01.jpg',
        'gallery' => [
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-03.jpg',
        ],
        'highlights' => [
            'Urgent AWB booking and airline capacity checks',
            'Airport recovery and onward road to port',
            'Export/import docs aligned to maritime use',
            'Express and standard air product mix',
            'Dangerous goods screening where applicable',
            'Tracking linked to vessel delivery windows',
        ],
        'process' => [
            ['title' => 'Assess', 'text' => 'Weight, dimensions, HS needs, and delivery port.'],
            ['title' => 'Book', 'text' => 'Secure uplift and confirm transit milestones.'],
            ['title' => 'Clear', 'text' => 'Manage export/import formalities.'],
            ['title' => 'Deliver', 'text' => 'Connect air arrival to port or onboard handover.'],
        ],
        'faqs' => [
            ['q' => 'Do you offer next-flight-out options?', 'a' => 'Where airline capacity and cut-offs allow, we book the fastest suitable uplift for critical cargo.'],
            ['q' => 'Can air freight include customs?', 'a' => 'Yes. Clearance can be bundled so cargo does not stall after landing.'],
            ['q' => 'How is this different from courier?', 'a' => 'Air freight suits heavier or special-handling consignments; courier and hand-carry suit documents and small urgent packages.'],
        ],
        'related' => ['express-courier', 'hand-carry', 'import-clearance', 'ship-spares-logistics'],
    ],

    'ocean-freight' => [
        'title' => 'Ocean Freight',
        'category' => 'freight_forwarding',
        'category_title' => 'Freight Forwarding',
        'meta_title' => 'Ocean Freight Forwarding | FCL LCL | MarineCaddie',
        'meta_description' => 'Ocean freight forwarding—FCL, LCL, and vessel-schedule-aware lanes for maritime and project cargo worldwide.',
        'meta_keywords' => 'ocean freight, FCL, LCL, sea freight forwarding, MarineCaddie',
        'excerpt' => 'Reliable FCL/LCL ocean moves aligned to vessel and project timelines.',
        'intro' => 'We arrange ocean freight that respects maritime realities—carrier selection, consolidations, and documentation that mesh with onward port or vessel delivery requirements.',
        'hero_image' => 'assets/img/services/service-03.jpg',
        'gallery' => [
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-02.jpg',
        ],
        'highlights' => [
            'FCL and LCL options across major trades',
            'Booking, documentation, and sailing updates',
            'Transhipment awareness for tight connections',
            'Project and break-bulk adjacent workflows',
            'Port of discharge coordination for last mile',
            'Cost-effective planning without losing control',
        ],
        'process' => [
            ['title' => 'Quote', 'text' => 'Commodity, ports, and preferred sailing window.'],
            ['title' => 'Book', 'text' => 'Space allocation and SI/BL workflows.'],
            ['title' => 'Sail', 'text' => 'Track vessel and notify of schedule changes.'],
            ['title' => 'Arrive', 'text' => 'Arrange clearance and inland/port delivery.'],
        ],
        'faqs' => [
            ['q' => 'Do you handle both FCL and LCL?', 'a' => 'Yes. We select the mode that fits your volume, urgency, and cost targets.'],
            ['q' => 'Can ocean freight feed ship spares programmes?', 'a' => 'Non-urgent spares and stores often move by ocean with planned vessel delivery.'],
            ['q' => 'Is multimodal included?', 'a' => 'Sea-plus-road or rail combinations can be designed under our multimodal service.'],
        ],
        'related' => ['multimodal-transport', 'road-transportation', 'break-bulk', 'export-clearance'],
    ],

    'road-transportation' => [
        'title' => 'Road Transportation',
        'category' => 'freight_forwarding',
        'category_title' => 'Freight Forwarding',
        'meta_title' => 'Road Transportation for Ports | MarineCaddie',
        'meta_description' => 'Port-to-warehouse and last-mile road transportation for maritime cargo, ship spares, and time-bound vessel deliveries.',
        'meta_keywords' => 'road transportation, port trucking, last mile freight, maritime road haulage, MarineCaddie',
        'excerpt' => 'Dependable road legs linking airports, warehouses, and vessel delivery points.',
        'intro' => 'Road is the connective tissue of maritime logistics. We arrange trucks and vans sized for spares, packages, and project pieces—timed to cut-offs and port gates.',
        'hero_image' => 'assets/img/services/service-02.jpg',
        'gallery' => [
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-01.jpg',
        ],
        'highlights' => [
            'Airport–port and warehouse–terminal trucking',
            'Vehicle match to cargo size and urgency',
            'Gate-in documentation support',
            'Live ETAs for operations desks',
            'Secure handling for high-value spares',
            'Works with air, ocean, and onboard delivery',
        ],
        'process' => [
            ['title' => 'Brief', 'text' => 'Pickup, delivery points, and time window.'],
            ['title' => 'Assign', 'text' => 'Select vehicle and driver brief.'],
            ['title' => 'Transit', 'text' => 'Track position and gate status.'],
            ['title' => 'Complete', 'text' => 'Capture POD and close the job.'],
        ],
        'faqs' => [
            ['q' => 'Do you cover cross-border road?', 'a' => 'Where partner networks and permits allow, we arrange regional road moves with proper documentation.'],
            ['q' => 'Can you handle oversized pieces?', 'a' => 'OOG and heavy pieces are planned under Special Projects with suitable equipment.'],
            ['q' => 'Is weekend transport available?', 'a' => 'Yes, subject to port/terminal operating hours and local regulations.'],
        ],
        'related' => ['onboard-delivery', 'air-freight', 'ocean-freight', 'multimodal-transport'],
    ],

    'express-courier' => [
        'title' => 'Express Courier',
        'category' => 'freight_forwarding',
        'category_title' => 'Freight Forwarding',
        'meta_title' => 'Express Courier for Maritime Documents & Spares | MarineCaddie',
        'meta_description' => 'Express courier solutions for urgent maritime documents and small packages—fast tracking with port delivery handoff options.',
        'meta_keywords' => 'express courier, urgent shipping, maritime courier, document courier, MarineCaddie',
        'excerpt' => 'Courier speed for documents and compact packages that must not miss the call.',
        'intro' => 'When envelopes, certificates, or compact spares need rapid door-to-door movement, our express courier pathways prioritise cut-offs and last-mile options into the port ecosystem.',
        'hero_image' => 'assets/img/services/service-01.jpg',
        'gallery' => [
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-03.jpg',
        ],
        'highlights' => [
            'Priority pickup and delivery windows',
            'Tracking for operations and procurement',
            'Suitable for docs and small components',
            'Can escalate to hand-carry when required',
            'Customs-aware international courier flows',
            'Port and office delivery addresses supported',
        ],
        'process' => [
            ['title' => 'Book', 'text' => 'Capture package details and urgency level.'],
            ['title' => 'Uplift', 'text' => 'Place into the fastest compliant network.'],
            ['title' => 'Monitor', 'text' => 'Watch checkpoints until final mile.'],
            ['title' => 'Handover', 'text' => 'Confirm receipt at office, agent, or vessel path.'],
        ],
        'faqs' => [
            ['q' => 'When should I choose courier over air freight?', 'a' => 'Courier suits smaller, simpler consignments; air freight suits heavier or more complex cargo.'],
            ['q' => 'Can you deliver to an agent’s office?', 'a' => 'Yes. Agent, chandler, or warehouse addresses are commonly used as handoff points.'],
            ['q' => 'What if customs holds the package?', 'a' => 'We escalate documentation and clearance support to release the shipment quickly.'],
        ],
        'related' => ['hand-carry', 'air-freight', 'ship-spares-logistics'],
    ],

    'hand-carry' => [
        'title' => 'Hand Carry',
        'category' => 'freight_forwarding',
        'category_title' => 'Freight Forwarding',
        'meta_title' => 'Hand Carry Service for Critical Spares | MarineCaddie',
        'meta_description' => 'Hand-carry of critical ship spares and documents by dedicated courier passenger—maximum control for the most urgent vessel needs.',
        'meta_keywords' => 'hand carry, onboard courier, dedicated courier, critical spare hand carry, MarineCaddie',
        'excerpt' => 'A dedicated person moves your critical package—maximum control when every hour counts.',
        'intro' => 'Hand carry is reserved for the highest-urgency scenarios: a part or document that must travel with a trusted escort through airports and into the port handover chain.',
        'hero_image' => 'assets/img/services/service-05.jpg',
        'gallery' => [
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-03.jpg',
        ],
        'highlights' => [
            'Assigned courier passenger end-to-end',
            'Airline and immigration planning for the escort',
            'Chain-of-custody accountability',
            'Direct liaison with receiver or agent',
            'Ideal for AOG / sailing-critical items',
            'Backup contingency if connections change',
        ],
        'process' => [
            ['title' => 'Qualify', 'text' => 'Confirm suitability, size, and compliance.'],
            ['title' => 'Deploy', 'text' => 'Book escort travel and package custody.'],
            ['title' => 'Transit', 'text' => 'Real-time updates through each checkpoint.'],
            ['title' => 'Deliver', 'text' => 'Person-to-person handover with POD.'],
        ],
        'faqs' => [
            ['q' => 'What size packages can be hand-carried?', 'a' => 'Typically cabin-compliant dimensions and weights; we advise early if the item exceeds airline cabin rules.'],
            ['q' => 'Is hand carry available worldwide?', 'a' => 'Availability depends on visa, flights, and destination access—we confirm feasibility before commitment.'],
            ['q' => 'How does cost compare to express air?', 'a' => 'Hand carry is a premium product; we recommend it only when schedule risk justifies the control.'],
        ],
        'related' => ['express-courier', 'air-freight', 'onboard-delivery'],
    ],

    'multimodal-transport' => [
        'title' => 'Multimodal Transport',
        'category' => 'freight_forwarding',
        'category_title' => 'Freight Forwarding',
        'meta_title' => 'Multimodal Transport Solutions | MarineCaddie',
        'meta_description' => 'Multimodal maritime logistics combining air, ocean, and road into one controlled plan from origin to vessel or project site.',
        'meta_keywords' => 'multimodal transport, combined transport, air ocean road, MarineCaddie',
        'excerpt' => 'One plan across air, ocean, and road—optimised for cost, transit, and vessel ETA.',
        'intro' => 'Few urgent maritime moves are single-mode. We design multimodal flows that protect the critical path while using slower legs where they save cost without risking the call.',
        'hero_image' => 'assets/img/services/service-03.jpg',
        'gallery' => [
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-02.jpg',
        ],
        'highlights' => [
            'Mode mix designed around vessel ETA',
            'Single ownership across handoffs',
            'Documentation continuity between legs',
            'Cost vs speed trade-off advice',
            'Exception playbooks at each transfer',
            'Fits spares, stores, and project pieces',
        ],
        'process' => [
            ['title' => 'Map ETA', 'text' => 'Anchor the plan to sailing or project gate.'],
            ['title' => 'Select modes', 'text' => 'Choose air/ocean/road segments deliberately.'],
            ['title' => 'Orchestrate', 'text' => 'Run each handoff with status control.'],
            ['title' => 'Finish', 'text' => 'Deliver to port, site, or onboard as scoped.'],
        ],
        'faqs' => [
            ['q' => 'Who is responsible at mode handoffs?', 'a' => 'MarineCaddie remains the coordinating owner so you are not chasing multiple vendors.'],
            ['q' => 'Can customs sit between modes?', 'a' => 'Yes—clearance steps are scheduled into the multimodal timeline.'],
            ['q' => 'Is multimodal good for project cargo?', 'a' => 'Often—heavy and OOG pieces may combine ocean mainhaul with specialised road delivery.'],
        ],
        'related' => ['ocean-freight', 'air-freight', 'road-transportation', 'project-cargo'],
    ],

    'tp-trans-shipment-clearance' => [
        'title' => 'TP Trans-shipment Clearance',
        'category' => 'customs_clearance',
        'category_title' => 'Customs Clearance',
        'meta_title' => 'TP / Trans-shipment Clearance | MarineCaddie',
        'meta_description' => 'TP and trans-shipment customs clearance for maritime cargo moving through hub ports without unnecessary delay.',
        'meta_keywords' => 'TP clearance, trans-shipment clearance, transit cargo customs, MarineCaddie',
        'excerpt' => 'Fast, accurate TP/trans-shipment formalities so cargo keeps moving through hub ports.',
        'intro' => 'Trans-shipment windows are unforgiving. Our customs team prepares TP documentation and filings so cargo connects onward without preventable holds.',
        'hero_image' => 'assets/img/services/service-04.jpg',
        'gallery' => [
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-02.jpg',
        ],
        'highlights' => [
            'TP/trans-shipment documentation expertise',
            'Alignment to connecting vessel or flight',
            'Hub-port process familiarity',
            'Escalation on holds and queries',
            'Linked to spare and freight desks',
            'Transparent status and duty exposure notes',
        ],
        'process' => [
            ['title' => 'Docs in', 'text' => 'Collect commercial and transport documents.'],
            ['title' => 'File', 'text' => 'Submit TP/trans-shipment declarations.'],
            ['title' => 'Clear', 'text' => 'Resolve queries and release cargo.'],
            ['title' => 'Connect', 'text' => 'Hand off to onwards carrier or agent.'],
        ],
        'faqs' => [
            ['q' => 'What documents are typically required?', 'a' => 'Commercial invoice, packing list, transport docs, and any permits relevant to the commodity and routing.'],
            ['q' => 'Can you work under tight connection times?', 'a' => 'We prioritise connection-critical filings and flag risks early if cut-offs are unrealistic.'],
            ['q' => 'Do you clear air and ocean TP moves?', 'a' => 'Yes—both air and ocean trans-shipment scenarios are supported.'],
        ],
        'related' => ['import-clearance', 'export-clearance', 'customs-consulting'],
    ],

    'import-clearance' => [
        'title' => 'Import Clearance',
        'category' => 'customs_clearance',
        'category_title' => 'Customs Clearance',
        'meta_title' => 'Import Customs Clearance | MarineCaddie',
        'meta_description' => 'Import customs clearance for maritime and spare-parts cargo—accurate filings, duty handling, and release timed to vessel needs.',
        'meta_keywords' => 'import clearance, import customs, maritime import clearance, MarineCaddie',
        'excerpt' => 'Import formalities handled accurately so cargo releases in time for the vessel or site.',
        'intro' => 'Import clearance protects schedules when done right. We classify, declare, and chase releases—keeping owners and procurement informed of duty implications and timing.',
        'hero_image' => 'assets/img/services/service-04.jpg',
        'gallery' => [
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-03.jpg',
        ],
        'highlights' => [
            'Import declaration and exam support',
            'HS classification guidance with suppliers',
            'Duty and VAT visibility before arrival',
            'Release coordination to road or onboard path',
            'Experience with ship spare commodities',
            'Post-clearance document packs for finance',
        ],
        'process' => [
            ['title' => 'Pre-alert', 'text' => 'Review docs before cargo arrival.'],
            ['title' => 'Declare', 'text' => 'File import entry correctly first time.'],
            ['title' => 'Release', 'text' => 'Pay duties/fees and secure release.'],
            ['title' => 'Dispatch', 'text' => 'Move cargo to the agreed next step.'],
        ],
        'faqs' => [
            ['q' => 'Can you estimate duties in advance?', 'a' => 'We provide indicative duty guidance based on HS and value; final assessment follows local customs rules.'],
            ['q' => 'What causes most import delays?', 'a' => 'Incomplete documents, valuation gaps, and restricted commodities—early document checks reduce risk.'],
            ['q' => 'Do you handle temporary imports?', 'a' => 'Where regimes exist, we advise and execute temporary import procedures for eligible cargo.'],
        ],
        'related' => ['export-clearance', 'duty-exemption', 'tp-trans-shipment-clearance', 'ship-spares-logistics'],
    ],

    'export-clearance' => [
        'title' => 'Export Clearance',
        'category' => 'customs_clearance',
        'category_title' => 'Customs Clearance',
        'meta_title' => 'Export Customs Clearance | MarineCaddie',
        'meta_description' => 'Export customs clearance for ship spares and maritime cargo—compliant filings that protect uplift and sailing deadlines.',
        'meta_keywords' => 'export clearance, export customs, shipping export formalities, MarineCaddie',
        'excerpt' => 'Compliant export clearance that protects airline and vessel cut-offs.',
        'intro' => 'Export holds cascade into missed flights and sailings. Our team prepares export entries and supports examinations so cargo uplifts on plan.',
        'hero_image' => 'assets/img/services/service-04.jpg',
        'gallery' => [
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-01.jpg',
        ],
        'highlights' => [
            'Export licence awareness where applicable',
            'Correct commercial documentation packs',
            'Cut-off aligned filing sequences',
            'Coordination with forwarder and carrier',
            'DG screening reminders for sensitive cargo',
            'Audit-friendly export file retention support',
        ],
        'process' => [
            ['title' => 'Assemble', 'text' => 'Invoice, packing list, and permits.'],
            ['title' => 'File', 'text' => 'Lodge export declaration.'],
            ['title' => 'Gate', 'text' => 'Clear cargo for terminal/airline acceptance.'],
            ['title' => 'Confirm', 'text' => 'Share clearance proof for uplift.'],
        ],
        'faqs' => [
            ['q' => 'Do you clear from non-maritime exporters?', 'a' => 'Yes—supplier-origin exports destined for vessels are a common workflow.'],
            ['q' => 'What if an exam is selected?', 'a' => 'We attend/liaise, supply missing data fast, and re-sequence uplift if needed.'],
            ['q' => 'Can export clearance pair with air freight?', 'a' => 'Export formalities are routinely bundled with air and ocean bookings.'],
        ],
        'related' => ['import-clearance', 'air-freight', 'ocean-freight', 'customs-consulting'],
    ],

    'duty-exemption' => [
        'title' => 'Duty Exemption',
        'category' => 'customs_clearance',
        'category_title' => 'Customs Clearance',
        'meta_title' => 'Duty Exemption Support | MarineCaddie',
        'meta_description' => 'Duty exemption and relief support for eligible maritime and ship-related cargo—documentation and process guidance with local customs practice.',
        'meta_keywords' => 'duty exemption, customs duty relief, maritime duty exemption, MarineCaddie',
        'excerpt' => 'Help claiming eligible duty exemptions and reliefs with the right supporting evidence.',
        'intro' => 'Some vessel and maritime cargo qualifies for special reliefs. We guide documentation and process so legitimate exemptions are pursued correctly—without exposing you to compliance risk.',
        'hero_image' => 'assets/img/services/service-04.jpg',
        'gallery' => [
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-02.jpg',
        ],
        'highlights' => [
            'Eligibility review against shipment facts',
            'Evidence and certificate checklist',
            'Coordination with customs brokers and authorities',
            'Clear notes on residual duty exposure',
            'Fits ship spare and stores programmes',
            'Post-entry amendment support where allowed',
        ],
        'process' => [
            ['title' => 'Review', 'text' => 'Assess cargo against exemption pathways.'],
            ['title' => 'Document', 'text' => 'Gather certificates and declarations.'],
            ['title' => 'Apply', 'text' => 'Lodge claims with the clearance entry.'],
            ['title' => 'Confirm', 'text' => 'Validate outcome and file for audit.'],
        ],
        'faqs' => [
            ['q' => 'Is exemption guaranteed?', 'a' => 'No. Approvals depend on local law and case facts; we maximise correct presentation of eligible claims.'],
            ['q' => 'How early should we engage you?', 'a' => 'Before shipment departs origin—certificates often need lead time.'],
            ['q' => 'Can exemptions apply on TP cargo?', 'a' => 'Rules vary; we advise based on routing and commodity specifics.'],
        ],
        'related' => ['import-clearance', 'customs-consulting', 'ship-spares-logistics'],
    ],

    'customs-consulting' => [
        'title' => 'Customs Consulting',
        'category' => 'customs_clearance',
        'category_title' => 'Customs Clearance',
        'meta_title' => 'Customs Consulting for Maritime Logistics | MarineCaddie',
        'meta_description' => 'Practical customs consulting for maritime logistics—HS guidance, process design, and risk reduction for recurring vessel support programmes.',
        'meta_keywords' => 'customs consulting, HS classification advice, maritime customs advisory, MarineCaddie',
        'excerpt' => 'Practical customs advice that reduces friction across recurring maritime logistics flows.',
        'intro' => 'Beyond single entries, we help teams design better document standards, classification habits, and playbooks for repeat spare and stores programmes.',
        'hero_image' => 'assets/img/services/service-04.jpg',
        'gallery' => [
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-03.jpg',
        ],
        'highlights' => [
            'HS and valuation process coaching',
            'Document SOP design for procurement',
            'Risk review for sensitive commodities',
            'Training touchpoints for ops teams',
            'Integration with freight and spare desks',
            'Clear written guidance you can reuse',
        ],
        'process' => [
            ['title' => 'Discover', 'text' => 'Map current pain points and shipment types.'],
            ['title' => 'Advise', 'text' => 'Recommend process and documentation fixes.'],
            ['title' => 'Pilot', 'text' => 'Apply guidance on live consignments.'],
            ['title' => 'Embed', 'text' => 'Leave a checklist your team can run.'],
        ],
        'faqs' => [
            ['q' => 'Is this legal advice?', 'a' => 'We provide operational customs process guidance; for formal legal opinions engage qualified counsel in the jurisdiction.'],
            ['q' => 'Do you consult only in the UAE?', 'a' => 'We advise across lanes we operate, with local partner input where required.'],
            ['q' => 'Can consulting include training?', 'a' => 'Yes—short briefings for procurement and ops teams are available.'],
        ],
        'related' => ['import-clearance', 'export-clearance', 'duty-exemption'],
    ],

    'oog-cargo' => [
        'title' => 'OOG Cargo',
        'category' => 'special_projects',
        'category_title' => 'Special Projects',
        'meta_title' => 'OOG Cargo Logistics | Out of Gauge | MarineCaddie',
        'meta_description' => 'Out-of-gauge cargo logistics—surveys, equipment planning, and multimodal moves for oversized maritime and project shipments.',
        'meta_keywords' => 'OOG cargo, out of gauge shipping, oversized cargo, MarineCaddie',
        'excerpt' => 'Out-of-gauge moves planned with the right equipment, permits, and port access.',
        'intro' => 'OOG shipments fail without early engineering of dimensions and route. We plan surveys, gear, and port handling so oversized pieces move safely and predictably.',
        'hero_image' => 'assets/img/services/service-06.jpg',
        'gallery' => [
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-01.jpg',
        ],
        'highlights' => [
            'Dimensional survey and lashing advice',
            'Specialised trailer and cranage planning',
            'Permit and escort coordination where needed',
            'Port and terminal capability checks',
            'Ocean OOG and break-bulk options',
            'Single project lead for stakeholders',
        ],
        'process' => [
            ['title' => 'Survey', 'text' => 'Confirm dimensions, weight, and CG.'],
            ['title' => 'Engineer', 'text' => 'Select mode, gear, and route.'],
            ['title' => 'Execute', 'text' => 'Move with method statements.'],
            ['title' => 'Deliver', 'text' => 'Position at site or vessel as scoped.'],
        ],
        'faqs' => [
            ['q' => 'When is a shipment considered OOG?', 'a' => 'When dimensions or weight exceed standard equipment envelopes for the chosen mode—we advise after reviewing drawing packs.'],
            ['q' => 'Do you arrange road escorts?', 'a' => 'Where local rules require escorts or permits, we include them in the plan.'],
            ['q' => 'Can OOG cargo go door-to-deck?', 'a' => 'Yes, when port and vessel receiving capabilities allow—planned jointly with agents.'],
        ],
        'related' => ['heavy-lift', 'break-bulk', 'project-cargo'],
    ],

    'dangerous-goods' => [
        'title' => 'Dangerous Goods',
        'category' => 'special_projects',
        'category_title' => 'Special Projects',
        'meta_title' => 'Dangerous Goods Shipping | DG Logistics | MarineCaddie',
        'meta_description' => 'Dangerous goods logistics support—classification awareness, compliant booking, and documentation for maritime and multimodal DG consignments.',
        'meta_keywords' => 'dangerous goods, DG shipping, IMDG, hazmat logistics, MarineCaddie',
        'excerpt' => 'Compliant handling pathways for DG consignments moving under maritime urgency.',
        'intro' => 'Dangerous goods demand correct classification, packing, and carrier acceptance. We coordinate DG documentation and bookings so compliant cargo still meets operational deadlines.',
        'hero_image' => 'assets/img/services/service-06.jpg',
        'gallery' => [
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-03.jpg',
        ],
        'highlights' => [
            'DG checklist before booking',
            'IMDG / IATA / ADR mode awareness',
            'Shipper declaration coordination',
            'Airline/ocean acceptance confirmation',
            'Segregation and stowage notes with carriers',
            'Escalation when paperwork is incomplete',
        ],
        'process' => [
            ['title' => 'Identify', 'text' => 'Confirm UN number, class, and packing group.'],
            ['title' => 'Prepare', 'text' => 'Ensure packing and marks/labels ready.'],
            ['title' => 'Book', 'text' => 'Place with DG-accepting carriers.'],
            ['title' => 'Monitor', 'text' => 'Track acceptance through to delivery.'],
        ],
        'faqs' => [
            ['q' => 'Do you certify DG packing?', 'a' => 'Shippers remain responsible for compliant packing; we guide requirements and refuse non-compliant uplift.'],
            ['q' => 'Can DG ship as hand carry?', 'a' => 'Almost never—airline passenger rules ban most DG. We advise compliant freight alternatives.'],
            ['q' => 'What slows DG shipments most?', 'a' => 'Missing SDS/DGD details and last-minute class changes—share documents early.'],
        ],
        'related' => ['air-freight', 'ocean-freight', 'project-cargo'],
    ],

    'heavy-lift' => [
        'title' => 'Heavy Lift',
        'category' => 'special_projects',
        'category_title' => 'Special Projects',
        'meta_title' => 'Heavy Lift Logistics | MarineCaddie',
        'meta_description' => 'Heavy lift logistics for maritime and industrial cargo—crane plans, route studies, and controlled moves from origin to site or vessel.',
        'meta_keywords' => 'heavy lift, heavy cargo logistics, crane lift shipping, MarineCaddie',
        'excerpt' => 'Controlled heavy-lift moves with gear plans that respect ground, quay, and vessel limits.',
        'intro' => 'Heavy lift is method-driven. We align crane charts, transport frames, and receiving points so mass and moments stay within safe envelopes throughout the journey.',
        'hero_image' => 'assets/img/services/service-06.jpg',
        'gallery' => [
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-01.jpg',
        ],
        'highlights' => [
            'Lift plans and equipment selection',
            'Route and ground-bearing considerations',
            'Quay and vessel receiving liaison',
            'Insurance and risk discussion support',
            'Combined with ocean or road mainhaul',
            'Dedicated project coordinator',
        ],
        'process' => [
            ['title' => 'Study', 'text' => 'Weight, lift points, and site constraints.'],
            ['title' => 'Plan', 'text' => 'Gear, sequence, and contingency.'],
            ['title' => 'Lift', 'text' => 'Execute under competent supervision.'],
            ['title' => 'Secure', 'text' => 'Stow/transport and final position.'],
        ],
        'faqs' => [
            ['q' => 'Do you supply cranes?', 'a' => 'We arrange suitable lift equipment through vetted vendors matched to the load and location.'],
            ['q' => 'Can heavy lift include ocean transport?', 'a' => 'Yes—vessel or barge options are evaluated with heavy-lift and break-bulk partners.'],
            ['q' => 'What information do you need first?', 'a' => 'Certified weight, drawings, lift points, and delivery site photos/specs.'],
        ],
        'related' => ['oog-cargo', 'break-bulk', 'project-cargo'],
    ],

    'break-bulk' => [
        'title' => 'Break Bulk',
        'category' => 'special_projects',
        'category_title' => 'Special Projects',
        'meta_title' => 'Break Bulk Shipping | MarineCaddie',
        'meta_description' => 'Break bulk shipping for non-containerised cargo—steel, machinery, and project pieces with careful stevedoring and documentation.',
        'meta_keywords' => 'break bulk, breakbulk shipping, non containerised cargo, MarineCaddie',
        'excerpt' => 'Break-bulk solutions for cargo that does not fit the container model.',
        'intro' => 'From steel to machinery, break bulk requires vessel selection, stevedore plans, and accurate tallies. We organise the ocean and port interface so pieces move as intended.',
        'hero_image' => 'assets/img/services/service-03.jpg',
        'gallery' => [
            'assets/img/services/service-detail-03.jpg',
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-02.jpg',
        ],
        'highlights' => [
            'Suitable vessel and space negotiation',
            'Stevedoring and tally coordination',
            'Lashing and securing attention',
            'Port of load/discharge capability checks',
            'Works with OOG and heavy-lift scopes',
            'Transparent milestone reporting',
        ],
        'process' => [
            ['title' => 'Define cargo', 'text' => 'Pack marks, weights, and handling notes.'],
            ['title' => 'Nominate', 'text' => 'Secure suitable break-bulk capacity.'],
            ['title' => 'Load', 'text' => 'Supervise load/lash with port partners.'],
            ['title' => 'Discharge', 'text' => 'Arrange receiving and onward move.'],
        ],
        'faqs' => [
            ['q' => 'Is break bulk slower than containers?', 'a' => 'Schedules differ by trade; we compare options against your gate dates.'],
            ['q' => 'Can part of a project move break bulk?', 'a' => 'Yes—mixed programmes often combine containerised and break-bulk lots.'],
            ['q' => 'Do you handle steel and pipes?', 'a' => 'Such commodities are common break-bulk candidates when specs allow.'],
        ],
        'related' => ['oog-cargo', 'ocean-freight', 'project-cargo'],
    ],

    'project-cargo' => [
        'title' => 'Project Cargo',
        'category' => 'special_projects',
        'category_title' => 'Special Projects',
        'meta_title' => 'Project Cargo Logistics | MarineCaddie',
        'meta_description' => 'End-to-end project cargo logistics—planning, multimodal execution, and port delivery for complex maritime and industrial projects.',
        'meta_keywords' => 'project cargo, project logistics, engineering cargo, MarineCaddie',
        'excerpt' => 'End-to-end project cargo control from factory to site or vessel—planned, multimodal, accountable.',
        'intro' => 'Project cargo succeeds on planning cadence. MarineCaddie assembles the method, vendors, and reporting rhythm so complex packages arrive in the right sequence for installation or vessel receiving.',
        'hero_image' => 'assets/img/services/service-06.jpg',
        'gallery' => [
            'assets/img/services/service-detail-01.jpg',
            'assets/img/services/service-detail-02.jpg',
            'assets/img/services/service-detail-03.jpg',
        ],
        'highlights' => [
            'Master schedule tied to project gates',
            'Mixed-mode execution under one lead',
            'OOG, heavy lift, and DG subsets handled',
            'Site and port interface management',
            'Cost tracking and exception logs',
            'Lessons-learned for follow-on phases',
        ],
        'process' => [
            ['title' => 'Kick-off', 'text' => 'Scope WBS, risks, and success metrics.'],
            ['title' => 'Plan', 'text' => 'Build multimodal and port method statements.'],
            ['title' => 'Execute', 'text' => 'Run packages with milestone control.'],
            ['title' => 'Close', 'text' => 'Deliver POD packs and project summary.'],
        ],
        'faqs' => [
            ['q' => 'How early should project cargo planning start?', 'a' => 'Ideally at fabrication/packing design—transport envelopes influence packaging choices.'],
            ['q' => 'Can you support multi-country projects?', 'a' => 'Yes—we coordinate origins and destinations across our network and partners.'],
            ['q' => 'Do you only move cargo or also consult?', 'a' => 'Both—planning consultancy and physical execution are available together or separately.'],
        ],
        'related' => ['oog-cargo', 'heavy-lift', 'break-bulk', 'multimodal-transport'],
    ],

];
